Dashboard/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

Penampungan/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import add_fren.urls as add_friend
import Profile.urls as profile
import update_status.urls as update_status
import Dashboard.urls as dashboard
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tambah-teman/', include(add_friend,namespace='tambah-teman')),
    url(r'^profile/', include('Profile.urls')),
    url(r'^update-status/', include(update_status, namespace='update-status')),
    url(r'^stats/', include(dashboard, namespace='stats')),
    url(r'^$', RedirectView.as_view(url='/update-status/', permanent=True)),
]

Profile/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

add_fren/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^post',views.setelah,name='post')
]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_todo

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_todo', add_todo, name='add_todo'),
]

Dashboard/models.py
from django.db import models

# Create your models here.

add_fren/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class LinkTeman(models.Model):
    nama=models.CharField(max_length=99)
    link=models.URLField()
    tanggal_nge_add=models.DateTimeField(default=timezone.now)

update_status/models.py
from django.db import models

class Todo(models.Model):
    title = models.CharField(max_length=27)
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

add_fren/forms.py
from django import forms

class FormLinkTeman(forms.Form):
    nama=forms.CharField(
        required=True,
        label='Nama',
        widget=forms.TextInput(attrs={'type':'text','placeholder':'Nama teman','class':'form-control'}),
        error_messages={'required':'Namanya tolong diisi'}
    )
    link=forms.URLField(
        required=True,
        label='Link',
        initial='https://',
        widget=forms.URLInput(attrs={'type':'text','placeholder':'Link heroku teman','class':'form-control'}),
        error_messages={'required':'Minta link-nya juga dong','invalid':'Link-nya isi yg bener plz (awalnya pake https://)'}
    )

update_status/forms.py
from django import forms

class Todo_Form(forms.Form):
    error_messages = {
        'required': 'Please fill this field',
    }
    description_attrs = {
        'type': 'text',
        'cols': 150,
        'rows': 3,
        'class': 'todo-form-textarea',
        'placeholder': 'Write Your story...'
    }

    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

Dashboard/views.py
from django.shortcuts import render
from update_status.models import Todo
# Create your views here.

response = {}

def index(request):
	number_of_status = Todo.objects.all().count()
	response['total'] = number_of_status
	if response['total'] != 0:
		last_post = Todo.objects.latest("created_date")
		response['last'] = last_post
	return render(request, 'Dashboard.html', response)

Profile/views.py
from django.shortcuts import render

mhs_name = 'Aliando Syarief'
birthday = '10-10-1997'
gender = 'Male'
expertise = ['Marketing', 'Collector', 'Public Speaking','Programmer', 'Designer', 'Architect']
desc = "Antique Expert, Experience marketer for 10 years"
email = 'oktavio.rei@gmail.com' 

def index(request):
    response = {'name':mhs_name, 'birthday':birthday, 'gender':gender, 'about_me':expertise, 'description':desc, 'email':email}
    html = 'Profile/Profile.html'
    return render(request, html,  response)

add_fren/views.py
from django.shortcuts import render,redirect
from .forms import FormLinkTeman
from .models import LinkTeman

# Create your views here.

def index(request):
    response={'input_link_teman':FormLinkTeman,'link_list':LinkTeman.objects.all()}
    return render(request,'add_fren/add_fren.html',response)

def setelah(request):
    form=FormLinkTeman(request.POST or None)
    if(request.method=='POST'and form.is_valid()):
        fren=LinkTeman(nama=request.POST['nama'],link=request.POST['link'])
        fren.save()
    return redirect('/tambah-teman/')

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Todo_Form
from .models import Todo

# Create your views here.
response = {}
def index(request):    
    response['author'] = ""
    todo = Todo.objects.all()
    response['todo'] = todo
    html = 'update_status/update_status.html'
    response['todo_form'] = Todo_Form
    return render(request, html, response)

def add_todo(request):
    form = Todo_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        todo = Todo(description=response['description'])
        todo.save()
        return HttpResponseRedirect('/update-status/')
    else:
        return HttpResponseRedirect('/update-status/')

Dashboard/templates/Dashboard.html
{% extends "base.html" %}
{% block content %}
<h1 class="main-title" align="center">Dashboard</h1 >
<hr/>
<p align="center"> <img width="200px" class="img-circle" id = 'image' align = 'middle' src= "http://www.hariandepok.com/wp-content/uploads/2015/07/aliando-syarief.jpg" alt="Profile"> </p>
<h3 align="center" class="main-title"><strong>Aliando Syarief</strong></h3>
<br>
<br>
<hr/>
<center><section>
	<h3>
		Total Post: {{ total }} Post
	</h3>	
	<h4>
		Last Post:
	</h4>
	<h4>
		"{{ last.description }}" 
	</h4>
	<h4> Created on {{ last.created_date }} </h4>
</section></center>
{% endblock %}

Profile/templates/Profile/Profile.html
<html>
    {% extends "base.html" %}
    
    {% block content %}
<head>
    <title>Profile</title>
    <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
    <div id="container">
        <div id="header">
            <h1 align="center">Profile</h1>
        <hr/>
        </div>
        <div id="content">
            <div id="nav">
                    <center>
                            <img width="200px" class="img-circle" src = 'https://i0.wp.com/kupastuntas.co/files/berita-hiburan/2017-05/di-bulan-ramadan-aliando-syarief-masuk-pesantren-01.jpg?ssl=1'>
                        </center>
                <h1 align="center">{{name}}</h1>
                <ul id = "menu" align="center">
                  <h2>
                        {% for ii in about_me %}
                        <li class="label label-info">{{ ii }}</li>
                        {% endfor %}
                  </h2>
                </ul>
            </div>

            <div id="main">
                    <table style="margin-left:400px" align="left">
                      <<h3>
                            <tr>
                              <td>Birthday:</td>
                              <td>{{birthday}}</td> 
                            </tr>
                            <tr>
                              <td>Gender:</td>
                              <td>{{gender}}</td> 
                            </tr>
                            <tr>
                              <td style="padding-right: 40px">Description:</td>
                              <td>{{description}}</td> 
                            </tr>
                            <tr>
                              <td>Email:</td>
                              <td>{{email}}</td> 
                            </tr>
                          </h3>
                    </table>
            </div>
        </div>
    </div>
</body>
{% endblock %}
</html>

add_fren/templates/add_fren/add_fren.html
{%extends "base.html" %}

{%block content%}
<h2 style="text-align:center;">Add Friend</h2>
<form id="form" method="POST" action="{%url 'tambah-teman:post'%}">
	{%csrf_token%}
	{{input_link_teman}}
	<br>
	<button type="submit" class="btn btn-default">Add</button>
</form>
<h2 style="text-align:center;"> List link ( ͡° ͜ʖ ͡°)</h2>

<div class="card">
	{%for i in link_list%}
	<div class="card-body">
		<h3 class="card-title"> - {{i.nama}} - </h3>
		<a href="{{i.link}}" class="card-link" style="color:Aqua;"> {{i.link}}</a>
		<p href="{{i.tanggal_nge_add}}" class="card-link" style="text-align:left;">{{i.tanggal_nge_add}}</p>
	</div>
	{%endfor%}
</div>
{%endblock%}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="LAB 4">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}" />    
    <title>
        {% block title %} LING IN! {% endblock %}
    </title>
</head>

<style>
    body {
        background-color: gray;
        background-repeat:no-repeat;
        background-size:200%;
        font-color: white;
        }
</style>

<body>
    <header>
        {% include "header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "footer.html" %}
        {% endblock %}
		
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

templates/footer.html
<p style="position:fixed;right:0;bottom:0;left:0;text-align:right"> LING IN! &copy; PARA GANTENG {{author}}</p>

templates/header.html
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<style type="text/css">
		body{margin: 0;}

		ul.topnav li.title{
			letter-spacing: 7px;
			color: Aqua;
			text-align: center;
		    padding: 5px 10px;
		    text-decoration: none;
		    font-size: 32px;
		    font-variant: small-caps;
		    font-family: Arial, Helvetica, sans-serif;
		}

		ul.topnav{
			list-style-type: none;
		    margin: 0;
		    padding: 0;
		    overflow: hidden;
		    background-color: black;
		}

		ul.topnav li{float: left;}

		ul.topnav li a{
			display: block;
		    color: white;
		    text-align: center;
		    padding: 14px 16px;
		    text-decoration: none;
		    font-family: Arial, Helvetica, sans-serif;
		    letter-spacing: 2px;
		}

		ul.topnav li a:hover:not(.active){background-color: #66b3ff;}

		ul.topnav li a.active{background-color: #a3a3c2;}

		ul.topnav li.left{float: left;}

		@media screen and (max-width: 600px){
			ul.topnav li.right,
			ul.topnav li{float: none;}
		}
	</style>
</head>

<body>
	<ul class="topnav" >
		<li class="title">LING IN!</li>
		<li><a class="nav-link" href="/update-status/">Status</a></li>
		<li><a class="nav-link" href="/profile/">Profile</a></li>
		<li><a class="nav-link" href="/tambah-teman/">Friends</a></li>
		<li><a class="nav-link" href="/stats/">Stats</a></li>
	</ul>
</body>
</html>

update_status/templates/update_status/update_status.html
{% extends "base.html" %}

{% block content %}
<h2 class="main-title">What Are You Doing Today?</h2>
<hr/>
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'update-status:add_todo' %}">
            {% csrf_token %}
            {{ todo_form }}
            <input id="submit" type="submit" class="btn btn-lg btn-info" value="Post">
            <br>
        </form>
    </div>
</section>
<section name="my-list" id="my-list">
    <div class="container">
		<div class="row">
			<div class="col-sm-offset-2 col-sm-8">
				<div class="container>
					<div class="flex">
						{% if todo %}
							{% for data in todo %}
								<div class="flex-item">
									<div class="to-do-list">
										<div class="to-do-list-name">
												<img class="img-circle" src="http://www.hariandepok.com/wp-content/uploads/2015/07/aliando-syarief.jpg" vertical-align="middle" width="40" height="40">
											<strong>Aliando Syarief</strong>
										</div>
										<div class="to-do-list-description">
											{{data.description}}
										</div>
										<div class="to-do-list-date-added">
											{{data.created_date}}
										</div>
									</div>
								</div>
							{% endfor %}
						{% else %}
						<div class="alert alert-danger text-center">
							<strong>Huft!</strong> Your timeline is empty:(
						</div>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
    </div>
</section>

{% endblock %}